service: ServerlessTransit
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        #- dynamodb:DeleteItem
        #- dynamodb:DescribeTable
        #- dynamodb:Scan
      Resource: 
        Fn::GetAtt: [ServerlessTransit, Arn]

package:
  exclude:
    - exclude-me.js
    - node_modules/**
    - package-lock.json
    - package.json
    - yarn.lock

functions:
  dynamodb_event:               # what an unhelpful name
    runtime: python3.7
    handler: handler.dynamodb_event
    # dependsOn:
    #   - ServerlessTransit
    # events:
    #   - stream: arn:aws:dynamodb:region:197161828500:table/serverless-transit/stream/
    # events:
    #   - stream:
    #       type: dynamodb
    #       arn:
    #         Fn::GetAtt: [ServerlessTransit, StreamArn ]

resources:
  Resources:
    ServerlessTransit:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-transit
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          # - AttributeName: subscriber_phone
          #   AttributeType: S
          # - AttributeName: subscriber_starttime
          #   AttributeType: S
          # - AttributeName: subscriber_endtime
          #   AttributeType: S
          # - AttributeName: transit_authority
          #   AttributeType: S
          # - AttributeName: transit_line
          #   AttributeType: S
          # - AttributeName: transit_station
          #   AttributeType: S
          # - AttributeName: report_source
          #   AttributeType: S
          # - AttributeName: report_text
          #   AttributeType: S
          # - AttributeName: status
          #   AttributeType: S
          # - AttributeName: details
          #   AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
            
    

